language: php
php:
  - '7.1'
dist: trusty
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - composer install
branches:
  only:
    - master
    - dev
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/test.sh
  - ./scripts/docker-publish.sh
after_success:
  - ./scripts/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always
