version: '3'
services:
  app:
    image: nginx
    build:
      context: .
      dockerfile: ./dev/nginx/Dockefile
    volumes:
      - ./dev/nginx/:/etc/nginx/conf.d
      - ./:/var/www/html  
    depends_on:
      - db
    ports: 
      - "8080:80"
    links:
      - php
  
  php:
    build:
      context: .
      dockerfile: ./dev/php/Dockerfile
    image: php7.1-fpm
    volumes:
      - ./:/var/www/html  

  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: rental
    ports:
      - "3333:3306"

  composer:
    image: composer
    volumes:
      - ./:/app
    command: ["composer", "install"]  
volumes:
  mysql-data:
