<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Notice;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

/**
 * NoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends \Doctrine\ORM\EntityRepository
{
    private $em;

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        $this->em = $em;
        parent::__construct($em, $class);
    }

    public function browse()
    {
        $em = $this->em;

        $qb = $this->createQueryBuilder('n')
            ->andWhere('n.isActive = :state')
            ->setParameter("state", true)
            ->getQuery();

        return $qb->execute();

    }

    public function add(Notice $notice)
    {
        $em = $this->em;
        try {
            $em->persist($notice);
            $em->flush();
        } catch (ORMException $e) {
        }
    }

    public function update(Notice $notice)
    {
        try {
            $this->em->flush();
        } catch (OptimisticLockException $e) {
        } catch (ORMException $e) {
        }
    }

    public function remove(Notice $notice)
    {
        $em = $this->em;

        try {
            $em->remove($notice);
            $em->flush();
        } catch (ORMException $e) {
        }

    }
}
