<?php

namespace AppBundle\Repository;

/**
 * RentalOrder
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalOrder extends \Doctrine\ORM\EntityRepository
{
}
