# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'


    #controllers
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Controller\RegisterController:
        arguments:
             $userService: '@AppBundle\Service\UserService'

    AppBundle\Controller\NoticeController:
        arguments:
             $noticeService: '@AppBundle\Service\NoticeService'

    AppBundle\Controller\OrderController:
        arguments:
             $orderService: '@AppBundle\Service\OrderService'
             $noticeService: '@AppBundle\Service\NoticeService'

    AppBundle\Controller\Admin\CarController:
        arguments:
             $carService: '@AppBundle\Service\CarService'

    #controllers - admin
    AppBundle\Controller\Admin\NoticeController:
        arguments:
             $noticeService: '@AppBundle\Service\NoticeService'

    AppBundle\Controller\Admin\OrderController:
        arguments:
             $orderService: '@AppBundle\Service\OrderService'
    #end - controllers -admin

    #services
    AppBundle\Service\UserService:
        arguments:
            $userRepository: '@AppBundle\Repository\UserRepository'
            $encrypter: '@AppBundle\Service\Encrypter'

    AppBundle\Service\NoticeService:
            arguments:
                $noticeRepository: '@AppBundle\Repository\NoticeRepository'

    AppBundle\Service\OrderService:
            arguments:
                $orderRepository: '@AppBundle\Repository\OrderRepository'

    AppBundle\Service\CarService:
            arguments:
                $carRepository: '@AppBundle\Repository\CarRepository'

    AppBundle\Service\FileUploader:
            arguments:
                [%photos_directory%]

    #repositories
    AppBundle\Repository\UserRepository:
            factory: 'doctrine.orm.entity_manager:getRepository'
            arguments: ['AppBundle\Entity\User']

    AppBundle\Repository\NoticeRepository:
            factory: 'doctrine.orm.entity_manager:getRepository'
            arguments: ['AppBundle\Entity\Notice']

    AppBundle\Repository\OrderRepository:
            factory: 'doctrine.orm.entity_manager:getRepository'
            arguments: ['AppBundle\Entity\Order']

    AppBundle\Repository\CarRepository:
            factory: 'doctrine.orm.entity_manager:getRepository'
            arguments: ['AppBundle\Entity\Car']

    #serializers
    AppBundle\Subscribers\NoticePostSerializeSubscriber:
        arguments:
          $router: '@router'
        tags:
          - { name: jms_serializer.event_subscriber, event: serializer.post_serialize}