AppBundle\Entity\Car:
    type: entity
    table: car
    repositoryClass: AppBundle\Repository\CarRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'id pojazdu'
            id: true
            column: id
            generator:
                strategy: IDENTITY
    oneToMany:
          notices:
            targetEntity: Notice
            mappedBy: car

          photos:
            targetEntity: Photo
            mappedBy: car
            cascade: [persist, remove]
    fields:
        model:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false
        brand:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false

        version:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false

        engine:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false
        fuel:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false

        mileage:
            type: integer
            nullable: false
            options:
                fixed: false

        productionYear:
            type: smallint
            nullable: false
            options:
                fixed: false

        gearshift:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false
        vin:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false

        airConditioning:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false

        registrationNumber:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false
lifecycleCallbacks: {  }