AppBundle\Entity\Order:
    type: entity
    table: rentalOrder
    repositoryClass: AppBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'notice id'
            id: true
            column: id
            generator:
                strategy: IDENTITY

    oneToOne:
        notice:
            targetEntity: Notice
            inversedBy: order
            joinColumn:
                name: notice_id
                referencedColumnName: id

        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: idUser

    fields:
        createdAt:
            type: datetime
            nullable: false
            lenght: 15
            options:
                fixed: false
                comment: "Created at date"

        rentFrom:
            type: datetime
            nullable: false
            length: 15
            options:
                fixed: false
                comment: 'Rent from date'

        rentTo:
            type: datetime
            nullable: false
            length: 15
            options:
                fixed: false
                comment: 'Rent to date'

        daysQuantity:
            type: smallint
            nullable: false
            lenght: 5
            options:
                fixed: false
                comment: 'Quanity of order days'

        totalCost:
            type: float
            nullable: false
            lenght: 10
            options:
                fixed: false
                comment: 'Total cost of order'

        status:
            type: string
            nullable: false
            columnDefinition: ENUM('pending', 'approved', 'rejected')
            options:
                fixed: false,
                comment: 'type'
            columnt: type


lifecycleCallbacks: {  }