AppBundle\Entity\Photo:
    type: entity
    table: photo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'photo id'
            id: true
            column: id
            generator:
                strategy: IDENTITY
    manyToOne:
        car:
            targetEntity: Car
            inversedBy: photos
            joinColumn:
                onDelete: "CASCADE"
                name: car_id
                referencedColumnName: id

    fields:
        filename:
            type: string
            nullable: false
            length: 63
            options:
                fixed: false
        extension:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
lifecycleCallbacks: {  }